version: "3.8"
services:
  beegoapp:
    image: beego-dev:latest    
    build:
      context: .
      target: dev
    container_name: beegoapp
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - beego_data:/app/data
    restart: always

volumes:
  beego_data: